[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GradedUnitRanges = "e2de450a-8a67-46c7-b59c-01d5a3d041c5"
LabelledNumbers = "f856a3a6-4152-4ec4-b2a7-02c1a55d7993"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
SymmetrySectors = "f8a8ad64-adbc-4fce-92f7-ffe2bb36a86e"

[compat]
Documenter = "1.8.1"
GradedUnitRanges = "0.1.7"
LabelledNumbers = "0.1.1"
Literate = "2.20.1"
SymmetrySectors = "0.1.5"
